// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto
#pragma warning(disable: 4125)
#pragma warning(disable: 4668)
#pragma warning(disable: 4577)


#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocol_2eproto;
namespace Protocol {
class C2P_ReportMove;
struct C2P_ReportMoveDefaultTypeInternal;
extern C2P_ReportMoveDefaultTypeInternal _C2P_ReportMove_default_instance_;
class C2P_RequestLogin;
struct C2P_RequestLoginDefaultTypeInternal;
extern C2P_RequestLoginDefaultTypeInternal _C2P_RequestLogin_default_instance_;
class C2P_RequestWorldData;
struct C2P_RequestWorldDataDefaultTypeInternal;
extern C2P_RequestWorldDataDefaultTypeInternal _C2P_RequestWorldData_default_instance_;
class P2C_ReportEnterUser;
struct P2C_ReportEnterUserDefaultTypeInternal;
extern P2C_ReportEnterUserDefaultTypeInternal _P2C_ReportEnterUser_default_instance_;
class P2C_ReportLeaveUser;
struct P2C_ReportLeaveUserDefaultTypeInternal;
extern P2C_ReportLeaveUserDefaultTypeInternal _P2C_ReportLeaveUser_default_instance_;
class P2C_ReportMove;
struct P2C_ReportMoveDefaultTypeInternal;
extern P2C_ReportMoveDefaultTypeInternal _P2C_ReportMove_default_instance_;
class P2C_ResultLogin;
struct P2C_ResultLoginDefaultTypeInternal;
extern P2C_ResultLoginDefaultTypeInternal _P2C_ResultLogin_default_instance_;
class P2C_ResultWorldData;
struct P2C_ResultWorldDataDefaultTypeInternal;
extern P2C_ResultWorldDataDefaultTypeInternal _P2C_ResultWorldData_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C2P_ReportMove* Arena::CreateMaybeMessage<::Protocol::C2P_ReportMove>(Arena*);
template<> ::Protocol::C2P_RequestLogin* Arena::CreateMaybeMessage<::Protocol::C2P_RequestLogin>(Arena*);
template<> ::Protocol::C2P_RequestWorldData* Arena::CreateMaybeMessage<::Protocol::C2P_RequestWorldData>(Arena*);
template<> ::Protocol::P2C_ReportEnterUser* Arena::CreateMaybeMessage<::Protocol::P2C_ReportEnterUser>(Arena*);
template<> ::Protocol::P2C_ReportLeaveUser* Arena::CreateMaybeMessage<::Protocol::P2C_ReportLeaveUser>(Arena*);
template<> ::Protocol::P2C_ReportMove* Arena::CreateMaybeMessage<::Protocol::P2C_ReportMove>(Arena*);
template<> ::Protocol::P2C_ResultLogin* Arena::CreateMaybeMessage<::Protocol::P2C_ResultLogin>(Arena*);
template<> ::Protocol::P2C_ResultWorldData* Arena::CreateMaybeMessage<::Protocol::P2C_ResultWorldData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class C2P_RequestLogin final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C2P_RequestLogin) */ {
 public:
  inline C2P_RequestLogin() : C2P_RequestLogin(nullptr) {}
  ~C2P_RequestLogin() override;
  explicit constexpr C2P_RequestLogin(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2P_RequestLogin(const C2P_RequestLogin& from);
  C2P_RequestLogin(C2P_RequestLogin&& from) noexcept
    : C2P_RequestLogin() {
    *this = ::std::move(from);
  }

  inline C2P_RequestLogin& operator=(const C2P_RequestLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2P_RequestLogin& operator=(C2P_RequestLogin&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2P_RequestLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2P_RequestLogin* internal_default_instance() {
    return reinterpret_cast<const C2P_RequestLogin*>(
               &_C2P_RequestLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C2P_RequestLogin& a, C2P_RequestLogin& b) {
    a.Swap(&b);
  }
  inline void Swap(C2P_RequestLogin* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2P_RequestLogin* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C2P_RequestLogin* New() const final {
    return new C2P_RequestLogin();
  }

  C2P_RequestLogin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C2P_RequestLogin>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C2P_RequestLogin& from);
  void MergeFrom(const C2P_RequestLogin& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2P_RequestLogin* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C2P_RequestLogin";
  }
  protected:
  explicit C2P_RequestLogin(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kPwFieldNumber = 2,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string pw = 2;
  void clear_pw();
  const std::string& pw() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pw(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pw();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_pw();
  void set_allocated_pw(std::string* pw);
  private:
  const std::string& _internal_pw() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pw(const std::string& value);
  std::string* _internal_mutable_pw();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C2P_RequestLogin)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pw_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class P2C_ResultLogin final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.P2C_ResultLogin) */ {
 public:
  inline P2C_ResultLogin() : P2C_ResultLogin(nullptr) {}
  ~P2C_ResultLogin() override;
  explicit constexpr P2C_ResultLogin(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  P2C_ResultLogin(const P2C_ResultLogin& from);
  P2C_ResultLogin(P2C_ResultLogin&& from) noexcept
    : P2C_ResultLogin() {
    *this = ::std::move(from);
  }

  inline P2C_ResultLogin& operator=(const P2C_ResultLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2C_ResultLogin& operator=(P2C_ResultLogin&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const P2C_ResultLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const P2C_ResultLogin* internal_default_instance() {
    return reinterpret_cast<const P2C_ResultLogin*>(
               &_P2C_ResultLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(P2C_ResultLogin& a, P2C_ResultLogin& b) {
    a.Swap(&b);
  }
  inline void Swap(P2C_ResultLogin* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2C_ResultLogin* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline P2C_ResultLogin* New() const final {
    return new P2C_ResultLogin();
  }

  P2C_ResultLogin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<P2C_ResultLogin>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const P2C_ResultLogin& from);
  void MergeFrom(const P2C_ResultLogin& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P2C_ResultLogin* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.P2C_ResultLogin";
  }
  protected:
  explicit P2C_ResultLogin(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // uint32 result = 1;
  void clear_result();
  ::PROTOBUF_NAMESPACE_ID::uint32 result() const;
  void set_result(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_result() const;
  void _internal_set_result(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.P2C_ResultLogin)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C2P_RequestWorldData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C2P_RequestWorldData) */ {
 public:
  inline C2P_RequestWorldData() : C2P_RequestWorldData(nullptr) {}
  ~C2P_RequestWorldData() override;
  explicit constexpr C2P_RequestWorldData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2P_RequestWorldData(const C2P_RequestWorldData& from);
  C2P_RequestWorldData(C2P_RequestWorldData&& from) noexcept
    : C2P_RequestWorldData() {
    *this = ::std::move(from);
  }

  inline C2P_RequestWorldData& operator=(const C2P_RequestWorldData& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2P_RequestWorldData& operator=(C2P_RequestWorldData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2P_RequestWorldData& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2P_RequestWorldData* internal_default_instance() {
    return reinterpret_cast<const C2P_RequestWorldData*>(
               &_C2P_RequestWorldData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(C2P_RequestWorldData& a, C2P_RequestWorldData& b) {
    a.Swap(&b);
  }
  inline void Swap(C2P_RequestWorldData* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2P_RequestWorldData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C2P_RequestWorldData* New() const final {
    return new C2P_RequestWorldData();
  }

  C2P_RequestWorldData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C2P_RequestWorldData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C2P_RequestWorldData& from);
  void MergeFrom(const C2P_RequestWorldData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2P_RequestWorldData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C2P_RequestWorldData";
  }
  protected:
  explicit C2P_RequestWorldData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Protocol.C2P_RequestWorldData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class P2C_ResultWorldData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.P2C_ResultWorldData) */ {
 public:
  inline P2C_ResultWorldData() : P2C_ResultWorldData(nullptr) {}
  ~P2C_ResultWorldData() override;
  explicit constexpr P2C_ResultWorldData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  P2C_ResultWorldData(const P2C_ResultWorldData& from);
  P2C_ResultWorldData(P2C_ResultWorldData&& from) noexcept
    : P2C_ResultWorldData() {
    *this = ::std::move(from);
  }

  inline P2C_ResultWorldData& operator=(const P2C_ResultWorldData& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2C_ResultWorldData& operator=(P2C_ResultWorldData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const P2C_ResultWorldData& default_instance() {
    return *internal_default_instance();
  }
  static inline const P2C_ResultWorldData* internal_default_instance() {
    return reinterpret_cast<const P2C_ResultWorldData*>(
               &_P2C_ResultWorldData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(P2C_ResultWorldData& a, P2C_ResultWorldData& b) {
    a.Swap(&b);
  }
  inline void Swap(P2C_ResultWorldData* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2C_ResultWorldData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline P2C_ResultWorldData* New() const final {
    return new P2C_ResultWorldData();
  }

  P2C_ResultWorldData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<P2C_ResultWorldData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const P2C_ResultWorldData& from);
  void MergeFrom(const P2C_ResultWorldData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P2C_ResultWorldData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.P2C_ResultWorldData";
  }
  protected:
  explicit P2C_ResultWorldData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsersFieldNumber = 1,
  };
  // repeated .Protocol.UserData Users = 1;
  int users_size() const;
  private:
  int _internal_users_size() const;
  public:
  void clear_users();
  ::Protocol::UserData* mutable_users(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::UserData >*
      mutable_users();
  private:
  const ::Protocol::UserData& _internal_users(int index) const;
  ::Protocol::UserData* _internal_add_users();
  public:
  const ::Protocol::UserData& users(int index) const;
  ::Protocol::UserData* add_users();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::UserData >&
      users() const;

  // @@protoc_insertion_point(class_scope:Protocol.P2C_ResultWorldData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::UserData > users_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class P2C_ReportEnterUser final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.P2C_ReportEnterUser) */ {
 public:
  inline P2C_ReportEnterUser() : P2C_ReportEnterUser(nullptr) {}
  ~P2C_ReportEnterUser() override;
  explicit constexpr P2C_ReportEnterUser(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  P2C_ReportEnterUser(const P2C_ReportEnterUser& from);
  P2C_ReportEnterUser(P2C_ReportEnterUser&& from) noexcept
    : P2C_ReportEnterUser() {
    *this = ::std::move(from);
  }

  inline P2C_ReportEnterUser& operator=(const P2C_ReportEnterUser& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2C_ReportEnterUser& operator=(P2C_ReportEnterUser&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const P2C_ReportEnterUser& default_instance() {
    return *internal_default_instance();
  }
  static inline const P2C_ReportEnterUser* internal_default_instance() {
    return reinterpret_cast<const P2C_ReportEnterUser*>(
               &_P2C_ReportEnterUser_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(P2C_ReportEnterUser& a, P2C_ReportEnterUser& b) {
    a.Swap(&b);
  }
  inline void Swap(P2C_ReportEnterUser* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2C_ReportEnterUser* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline P2C_ReportEnterUser* New() const final {
    return new P2C_ReportEnterUser();
  }

  P2C_ReportEnterUser* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<P2C_ReportEnterUser>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const P2C_ReportEnterUser& from);
  void MergeFrom(const P2C_ReportEnterUser& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P2C_ReportEnterUser* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.P2C_ReportEnterUser";
  }
  protected:
  explicit P2C_ReportEnterUser(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserFieldNumber = 1,
  };
  // .Protocol.UserData User = 1;
  bool has_user() const;
  private:
  bool _internal_has_user() const;
  public:
  void clear_user();
  const ::Protocol::UserData& user() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::UserData* release_user();
  ::Protocol::UserData* mutable_user();
  void set_allocated_user(::Protocol::UserData* user);
  private:
  const ::Protocol::UserData& _internal_user() const;
  ::Protocol::UserData* _internal_mutable_user();
  public:
  void unsafe_arena_set_allocated_user(
      ::Protocol::UserData* user);
  ::Protocol::UserData* unsafe_arena_release_user();

  // @@protoc_insertion_point(class_scope:Protocol.P2C_ReportEnterUser)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Protocol::UserData* user_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class P2C_ReportLeaveUser final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.P2C_ReportLeaveUser) */ {
 public:
  inline P2C_ReportLeaveUser() : P2C_ReportLeaveUser(nullptr) {}
  ~P2C_ReportLeaveUser() override;
  explicit constexpr P2C_ReportLeaveUser(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  P2C_ReportLeaveUser(const P2C_ReportLeaveUser& from);
  P2C_ReportLeaveUser(P2C_ReportLeaveUser&& from) noexcept
    : P2C_ReportLeaveUser() {
    *this = ::std::move(from);
  }

  inline P2C_ReportLeaveUser& operator=(const P2C_ReportLeaveUser& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2C_ReportLeaveUser& operator=(P2C_ReportLeaveUser&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const P2C_ReportLeaveUser& default_instance() {
    return *internal_default_instance();
  }
  static inline const P2C_ReportLeaveUser* internal_default_instance() {
    return reinterpret_cast<const P2C_ReportLeaveUser*>(
               &_P2C_ReportLeaveUser_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(P2C_ReportLeaveUser& a, P2C_ReportLeaveUser& b) {
    a.Swap(&b);
  }
  inline void Swap(P2C_ReportLeaveUser* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2C_ReportLeaveUser* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline P2C_ReportLeaveUser* New() const final {
    return new P2C_ReportLeaveUser();
  }

  P2C_ReportLeaveUser* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<P2C_ReportLeaveUser>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const P2C_ReportLeaveUser& from);
  void MergeFrom(const P2C_ReportLeaveUser& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P2C_ReportLeaveUser* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.P2C_ReportLeaveUser";
  }
  protected:
  explicit P2C_ReportLeaveUser(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserKeyFieldNumber = 1,
  };
  // uint64 UserKey = 1;
  void clear_userkey();
  ::PROTOBUF_NAMESPACE_ID::uint64 userkey() const;
  void set_userkey(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_userkey() const;
  void _internal_set_userkey(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.P2C_ReportLeaveUser)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 userkey_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C2P_ReportMove final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C2P_ReportMove) */ {
 public:
  inline C2P_ReportMove() : C2P_ReportMove(nullptr) {}
  ~C2P_ReportMove() override;
  explicit constexpr C2P_ReportMove(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2P_ReportMove(const C2P_ReportMove& from);
  C2P_ReportMove(C2P_ReportMove&& from) noexcept
    : C2P_ReportMove() {
    *this = ::std::move(from);
  }

  inline C2P_ReportMove& operator=(const C2P_ReportMove& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2P_ReportMove& operator=(C2P_ReportMove&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2P_ReportMove& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2P_ReportMove* internal_default_instance() {
    return reinterpret_cast<const C2P_ReportMove*>(
               &_C2P_ReportMove_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(C2P_ReportMove& a, C2P_ReportMove& b) {
    a.Swap(&b);
  }
  inline void Swap(C2P_ReportMove* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2P_ReportMove* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C2P_ReportMove* New() const final {
    return new C2P_ReportMove();
  }

  C2P_ReportMove* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C2P_ReportMove>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C2P_ReportMove& from);
  void MergeFrom(const C2P_ReportMove& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2P_ReportMove* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C2P_ReportMove";
  }
  protected:
  explicit C2P_ReportMove(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPosDataFieldNumber = 1,
    kStateFieldNumber = 2,
  };
  // .Protocol.PositionData PosData = 1;
  bool has_posdata() const;
  private:
  bool _internal_has_posdata() const;
  public:
  void clear_posdata();
  const ::Protocol::PositionData& posdata() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::PositionData* release_posdata();
  ::Protocol::PositionData* mutable_posdata();
  void set_allocated_posdata(::Protocol::PositionData* posdata);
  private:
  const ::Protocol::PositionData& _internal_posdata() const;
  ::Protocol::PositionData* _internal_mutable_posdata();
  public:
  void unsafe_arena_set_allocated_posdata(
      ::Protocol::PositionData* posdata);
  ::Protocol::PositionData* unsafe_arena_release_posdata();

  // .Protocol.PlayerState State = 2;
  void clear_state();
  ::Protocol::PlayerState state() const;
  void set_state(::Protocol::PlayerState value);
  private:
  ::Protocol::PlayerState _internal_state() const;
  void _internal_set_state(::Protocol::PlayerState value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C2P_ReportMove)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Protocol::PositionData* posdata_;
  int state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class P2C_ReportMove final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.P2C_ReportMove) */ {
 public:
  inline P2C_ReportMove() : P2C_ReportMove(nullptr) {}
  ~P2C_ReportMove() override;
  explicit constexpr P2C_ReportMove(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  P2C_ReportMove(const P2C_ReportMove& from);
  P2C_ReportMove(P2C_ReportMove&& from) noexcept
    : P2C_ReportMove() {
    *this = ::std::move(from);
  }

  inline P2C_ReportMove& operator=(const P2C_ReportMove& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2C_ReportMove& operator=(P2C_ReportMove&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const P2C_ReportMove& default_instance() {
    return *internal_default_instance();
  }
  static inline const P2C_ReportMove* internal_default_instance() {
    return reinterpret_cast<const P2C_ReportMove*>(
               &_P2C_ReportMove_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(P2C_ReportMove& a, P2C_ReportMove& b) {
    a.Swap(&b);
  }
  inline void Swap(P2C_ReportMove* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2C_ReportMove* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline P2C_ReportMove* New() const final {
    return new P2C_ReportMove();
  }

  P2C_ReportMove* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<P2C_ReportMove>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const P2C_ReportMove& from);
  void MergeFrom(const P2C_ReportMove& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P2C_ReportMove* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.P2C_ReportMove";
  }
  protected:
  explicit P2C_ReportMove(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPosDataFieldNumber = 2,
    kUserKeyFieldNumber = 1,
    kStateFieldNumber = 3,
  };
  // .Protocol.PositionData PosData = 2;
  bool has_posdata() const;
  private:
  bool _internal_has_posdata() const;
  public:
  void clear_posdata();
  const ::Protocol::PositionData& posdata() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::PositionData* release_posdata();
  ::Protocol::PositionData* mutable_posdata();
  void set_allocated_posdata(::Protocol::PositionData* posdata);
  private:
  const ::Protocol::PositionData& _internal_posdata() const;
  ::Protocol::PositionData* _internal_mutable_posdata();
  public:
  void unsafe_arena_set_allocated_posdata(
      ::Protocol::PositionData* posdata);
  ::Protocol::PositionData* unsafe_arena_release_posdata();

  // uint64 UserKey = 1;
  void clear_userkey();
  ::PROTOBUF_NAMESPACE_ID::uint64 userkey() const;
  void set_userkey(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_userkey() const;
  void _internal_set_userkey(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .Protocol.PlayerState State = 3;
  void clear_state();
  ::Protocol::PlayerState state() const;
  void set_state(::Protocol::PlayerState value);
  private:
  ::Protocol::PlayerState _internal_state() const;
  void _internal_set_state(::Protocol::PlayerState value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.P2C_ReportMove)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Protocol::PositionData* posdata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 userkey_;
  int state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C2P_RequestLogin

// string id = 1;
inline void C2P_RequestLogin::clear_id() {
  id_.ClearToEmpty();
}
inline const std::string& C2P_RequestLogin::id() const {
  // @@protoc_insertion_point(field_get:Protocol.C2P_RequestLogin.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C2P_RequestLogin::set_id(ArgT0&& arg0, ArgT... args) {
 
 id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C2P_RequestLogin.id)
}
inline std::string* C2P_RequestLogin::mutable_id() {
  // @@protoc_insertion_point(field_mutable:Protocol.C2P_RequestLogin.id)
  return _internal_mutable_id();
}
inline const std::string& C2P_RequestLogin::_internal_id() const {
  return id_.Get();
}
inline void C2P_RequestLogin::_internal_set_id(const std::string& value) {
  
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* C2P_RequestLogin::_internal_mutable_id() {
  
  return id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* C2P_RequestLogin::release_id() {
  // @@protoc_insertion_point(field_release:Protocol.C2P_RequestLogin.id)
  return id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void C2P_RequestLogin::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.C2P_RequestLogin.id)
}

// string pw = 2;
inline void C2P_RequestLogin::clear_pw() {
  pw_.ClearToEmpty();
}
inline const std::string& C2P_RequestLogin::pw() const {
  // @@protoc_insertion_point(field_get:Protocol.C2P_RequestLogin.pw)
  return _internal_pw();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C2P_RequestLogin::set_pw(ArgT0&& arg0, ArgT... args) {
 
 pw_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C2P_RequestLogin.pw)
}
inline std::string* C2P_RequestLogin::mutable_pw() {
  // @@protoc_insertion_point(field_mutable:Protocol.C2P_RequestLogin.pw)
  return _internal_mutable_pw();
}
inline const std::string& C2P_RequestLogin::_internal_pw() const {
  return pw_.Get();
}
inline void C2P_RequestLogin::_internal_set_pw(const std::string& value) {
  
  pw_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* C2P_RequestLogin::_internal_mutable_pw() {
  
  return pw_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* C2P_RequestLogin::release_pw() {
  // @@protoc_insertion_point(field_release:Protocol.C2P_RequestLogin.pw)
  return pw_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void C2P_RequestLogin::set_allocated_pw(std::string* pw) {
  if (pw != nullptr) {
    
  } else {
    
  }
  pw_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pw,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.C2P_RequestLogin.pw)
}

// -------------------------------------------------------------------

// P2C_ResultLogin

// uint32 result = 1;
inline void P2C_ResultLogin::clear_result() {
  result_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 P2C_ResultLogin::_internal_result() const {
  return result_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 P2C_ResultLogin::result() const {
  // @@protoc_insertion_point(field_get:Protocol.P2C_ResultLogin.result)
  return _internal_result();
}
inline void P2C_ResultLogin::_internal_set_result(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  result_ = value;
}
inline void P2C_ResultLogin::set_result(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:Protocol.P2C_ResultLogin.result)
}

// -------------------------------------------------------------------

// C2P_RequestWorldData

// -------------------------------------------------------------------

// P2C_ResultWorldData

// repeated .Protocol.UserData Users = 1;
inline int P2C_ResultWorldData::_internal_users_size() const {
  return users_.size();
}
inline int P2C_ResultWorldData::users_size() const {
  return _internal_users_size();
}
inline ::Protocol::UserData* P2C_ResultWorldData::mutable_users(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.P2C_ResultWorldData.Users)
  return users_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::UserData >*
P2C_ResultWorldData::mutable_users() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.P2C_ResultWorldData.Users)
  return &users_;
}
inline const ::Protocol::UserData& P2C_ResultWorldData::_internal_users(int index) const {
  return users_.Get(index);
}
inline const ::Protocol::UserData& P2C_ResultWorldData::users(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.P2C_ResultWorldData.Users)
  return _internal_users(index);
}
inline ::Protocol::UserData* P2C_ResultWorldData::_internal_add_users() {
  return users_.Add();
}
inline ::Protocol::UserData* P2C_ResultWorldData::add_users() {
  // @@protoc_insertion_point(field_add:Protocol.P2C_ResultWorldData.Users)
  return _internal_add_users();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::UserData >&
P2C_ResultWorldData::users() const {
  // @@protoc_insertion_point(field_list:Protocol.P2C_ResultWorldData.Users)
  return users_;
}

// -------------------------------------------------------------------

// P2C_ReportEnterUser

// .Protocol.UserData User = 1;
inline bool P2C_ReportEnterUser::_internal_has_user() const {
  return this != internal_default_instance() && user_ != nullptr;
}
inline bool P2C_ReportEnterUser::has_user() const {
  return _internal_has_user();
}
inline const ::Protocol::UserData& P2C_ReportEnterUser::_internal_user() const {
  const ::Protocol::UserData* p = user_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::UserData&>(
      ::Protocol::_UserData_default_instance_);
}
inline const ::Protocol::UserData& P2C_ReportEnterUser::user() const {
  // @@protoc_insertion_point(field_get:Protocol.P2C_ReportEnterUser.User)
  return _internal_user();
}
inline void P2C_ReportEnterUser::unsafe_arena_set_allocated_user(
    ::Protocol::UserData* user) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_);
  }
  user_ = user;
  if (user) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.P2C_ReportEnterUser.User)
}
inline ::Protocol::UserData* P2C_ReportEnterUser::release_user() {
  
  ::Protocol::UserData* temp = user_;
  user_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::UserData* P2C_ReportEnterUser::unsafe_arena_release_user() {
  // @@protoc_insertion_point(field_release:Protocol.P2C_ReportEnterUser.User)
  
  ::Protocol::UserData* temp = user_;
  user_ = nullptr;
  return temp;
}
inline ::Protocol::UserData* P2C_ReportEnterUser::_internal_mutable_user() {
  
  if (user_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::UserData>(GetArenaForAllocation());
    user_ = p;
  }
  return user_;
}
inline ::Protocol::UserData* P2C_ReportEnterUser::mutable_user() {
  // @@protoc_insertion_point(field_mutable:Protocol.P2C_ReportEnterUser.User)
  return _internal_mutable_user();
}
inline void P2C_ReportEnterUser::set_allocated_user(::Protocol::UserData* user) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_);
  }
  if (user) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(user));
    if (message_arena != submessage_arena) {
      user = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, user, submessage_arena);
    }
    
  } else {
    
  }
  user_ = user;
  // @@protoc_insertion_point(field_set_allocated:Protocol.P2C_ReportEnterUser.User)
}

// -------------------------------------------------------------------

// P2C_ReportLeaveUser

// uint64 UserKey = 1;
inline void P2C_ReportLeaveUser::clear_userkey() {
  userkey_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 P2C_ReportLeaveUser::_internal_userkey() const {
  return userkey_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 P2C_ReportLeaveUser::userkey() const {
  // @@protoc_insertion_point(field_get:Protocol.P2C_ReportLeaveUser.UserKey)
  return _internal_userkey();
}
inline void P2C_ReportLeaveUser::_internal_set_userkey(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  userkey_ = value;
}
inline void P2C_ReportLeaveUser::set_userkey(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_userkey(value);
  // @@protoc_insertion_point(field_set:Protocol.P2C_ReportLeaveUser.UserKey)
}

// -------------------------------------------------------------------

// C2P_ReportMove

// .Protocol.PositionData PosData = 1;
inline bool C2P_ReportMove::_internal_has_posdata() const {
  return this != internal_default_instance() && posdata_ != nullptr;
}
inline bool C2P_ReportMove::has_posdata() const {
  return _internal_has_posdata();
}
inline const ::Protocol::PositionData& C2P_ReportMove::_internal_posdata() const {
  const ::Protocol::PositionData* p = posdata_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PositionData&>(
      ::Protocol::_PositionData_default_instance_);
}
inline const ::Protocol::PositionData& C2P_ReportMove::posdata() const {
  // @@protoc_insertion_point(field_get:Protocol.C2P_ReportMove.PosData)
  return _internal_posdata();
}
inline void C2P_ReportMove::unsafe_arena_set_allocated_posdata(
    ::Protocol::PositionData* posdata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(posdata_);
  }
  posdata_ = posdata;
  if (posdata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C2P_ReportMove.PosData)
}
inline ::Protocol::PositionData* C2P_ReportMove::release_posdata() {
  
  ::Protocol::PositionData* temp = posdata_;
  posdata_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::PositionData* C2P_ReportMove::unsafe_arena_release_posdata() {
  // @@protoc_insertion_point(field_release:Protocol.C2P_ReportMove.PosData)
  
  ::Protocol::PositionData* temp = posdata_;
  posdata_ = nullptr;
  return temp;
}
inline ::Protocol::PositionData* C2P_ReportMove::_internal_mutable_posdata() {
  
  if (posdata_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::PositionData>(GetArenaForAllocation());
    posdata_ = p;
  }
  return posdata_;
}
inline ::Protocol::PositionData* C2P_ReportMove::mutable_posdata() {
  // @@protoc_insertion_point(field_mutable:Protocol.C2P_ReportMove.PosData)
  return _internal_mutable_posdata();
}
inline void C2P_ReportMove::set_allocated_posdata(::Protocol::PositionData* posdata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(posdata_);
  }
  if (posdata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(posdata));
    if (message_arena != submessage_arena) {
      posdata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, posdata, submessage_arena);
    }
    
  } else {
    
  }
  posdata_ = posdata;
  // @@protoc_insertion_point(field_set_allocated:Protocol.C2P_ReportMove.PosData)
}

// .Protocol.PlayerState State = 2;
inline void C2P_ReportMove::clear_state() {
  state_ = 0;
}
inline ::Protocol::PlayerState C2P_ReportMove::_internal_state() const {
  return static_cast< ::Protocol::PlayerState >(state_);
}
inline ::Protocol::PlayerState C2P_ReportMove::state() const {
  // @@protoc_insertion_point(field_get:Protocol.C2P_ReportMove.State)
  return _internal_state();
}
inline void C2P_ReportMove::_internal_set_state(::Protocol::PlayerState value) {
  
  state_ = value;
}
inline void C2P_ReportMove::set_state(::Protocol::PlayerState value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protocol.C2P_ReportMove.State)
}

// -------------------------------------------------------------------

// P2C_ReportMove

// uint64 UserKey = 1;
inline void P2C_ReportMove::clear_userkey() {
  userkey_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 P2C_ReportMove::_internal_userkey() const {
  return userkey_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 P2C_ReportMove::userkey() const {
  // @@protoc_insertion_point(field_get:Protocol.P2C_ReportMove.UserKey)
  return _internal_userkey();
}
inline void P2C_ReportMove::_internal_set_userkey(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  userkey_ = value;
}
inline void P2C_ReportMove::set_userkey(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_userkey(value);
  // @@protoc_insertion_point(field_set:Protocol.P2C_ReportMove.UserKey)
}

// .Protocol.PositionData PosData = 2;
inline bool P2C_ReportMove::_internal_has_posdata() const {
  return this != internal_default_instance() && posdata_ != nullptr;
}
inline bool P2C_ReportMove::has_posdata() const {
  return _internal_has_posdata();
}
inline const ::Protocol::PositionData& P2C_ReportMove::_internal_posdata() const {
  const ::Protocol::PositionData* p = posdata_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PositionData&>(
      ::Protocol::_PositionData_default_instance_);
}
inline const ::Protocol::PositionData& P2C_ReportMove::posdata() const {
  // @@protoc_insertion_point(field_get:Protocol.P2C_ReportMove.PosData)
  return _internal_posdata();
}
inline void P2C_ReportMove::unsafe_arena_set_allocated_posdata(
    ::Protocol::PositionData* posdata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(posdata_);
  }
  posdata_ = posdata;
  if (posdata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.P2C_ReportMove.PosData)
}
inline ::Protocol::PositionData* P2C_ReportMove::release_posdata() {
  
  ::Protocol::PositionData* temp = posdata_;
  posdata_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::PositionData* P2C_ReportMove::unsafe_arena_release_posdata() {
  // @@protoc_insertion_point(field_release:Protocol.P2C_ReportMove.PosData)
  
  ::Protocol::PositionData* temp = posdata_;
  posdata_ = nullptr;
  return temp;
}
inline ::Protocol::PositionData* P2C_ReportMove::_internal_mutable_posdata() {
  
  if (posdata_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::PositionData>(GetArenaForAllocation());
    posdata_ = p;
  }
  return posdata_;
}
inline ::Protocol::PositionData* P2C_ReportMove::mutable_posdata() {
  // @@protoc_insertion_point(field_mutable:Protocol.P2C_ReportMove.PosData)
  return _internal_mutable_posdata();
}
inline void P2C_ReportMove::set_allocated_posdata(::Protocol::PositionData* posdata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(posdata_);
  }
  if (posdata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(posdata));
    if (message_arena != submessage_arena) {
      posdata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, posdata, submessage_arena);
    }
    
  } else {
    
  }
  posdata_ = posdata;
  // @@protoc_insertion_point(field_set_allocated:Protocol.P2C_ReportMove.PosData)
}

// .Protocol.PlayerState State = 3;
inline void P2C_ReportMove::clear_state() {
  state_ = 0;
}
inline ::Protocol::PlayerState P2C_ReportMove::_internal_state() const {
  return static_cast< ::Protocol::PlayerState >(state_);
}
inline ::Protocol::PlayerState P2C_ReportMove::state() const {
  // @@protoc_insertion_point(field_get:Protocol.P2C_ReportMove.State)
  return _internal_state();
}
inline void P2C_ReportMove::_internal_set_state(::Protocol::PlayerState value) {
  
  state_ = value;
}
inline void P2C_ReportMove::set_state(::Protocol::PlayerState value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protocol.P2C_ReportMove.State)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
